from math import sqrt

# GRAPH
GRAPH_VIEW_WIDTH = 640
GRAPH_VIEW_HEIGHT = 600
RADIUS = 12
RADIUS_SQRT = sqrt(RADIUS)
VERTEX_FONT_SIZE = RADIUS
EDGE_WIDTH = 1.35
EDGE_WIDTH_WIDER = EDGE_WIDTH * 1.75
APEX_DISTANCE = 55

WEIGHT_FONT_SIZE = 13

# GRAPH FRAME COLORS
GRAPH_BG_COLOR_DARK = '#242424'
GRAPH_BG_COLOR_LIGHT = '#ebebeb'

# VERTEX COLORS
VERTEX_BG_COLOR_DARK = '#B4F8C8'
VERTEX_FG_COLOR_DARK = '#04230E'
VERTEX_COLOR_CHANGE_BG_DARK = '#F8D210'
VERTEX_COLOR_CHANGE_FG_DARK = 'black'

VERTEX_BG_COLOR_PRESSED_RB = "purple"
VERTEX_FG_COLOR_PRESSED_RB = "red"

VERTEX_BG_COLOR_LIGHT = '#03C988'
VERTEX_FG_COLOR_LIGHT = '#13005A'
VERTEX_COLOR_CHANGE_BG_LIGHT = '#F8D210'
VERTEX_COLOR_CHANGE_FG_LIGHT = 'black'

# EDGE COLORS
EDGE_COLOR_DARK = '#D4F1F4'
EDGE_COLOR_CHANGE_DARK = '#F8D210'
WEIGHT_COLOR_DARK = '#B4F8C8'
WEIGHT_COLOR_CHANGE_DARK = 'red'

EDGE_COLOR_LIGHT = '#13005A'
EDGE_COLOR_CHANGE_LIGHT = '#F8D210'
WEIGHT_COLOR_LIGHT = '#03C988'
WEIGHT_COLOR_CHANGE_LIGHT = 'red'

# BUTTON PANEL
BUTTONS_VIEW_WIDTH = 200
BUTTONS_VIEW_HEIGHT = 600
BUTTON_WIDTH = 30
BUTTON_HEIGHT = 5
BUTTONS_PANEL_BG_COLOR = '#164863'
BUTTONS_PANEL_SIZE_BG_COLOR = '#222831'
BUTTONS_PANEL_SIZE_FG_COLOR = '#EEEEEE'
BUTTON_BG_COLOR = '#222831'
BUTTON_FG_COLOR = '#EEEEEE'
FONT = "Oswald 13 bold"

WINDOW_HEIGHT = 600
WINDOW_WIDTH = 950

LEFT_FRAME_WIDTH = 140

NEXT_TO_MAIN_WINDOW = WINDOW_WIDTH + 200
BELOW_MAIN_WINDOW = WINDOW_HEIGHT + 150

GENERATE_GRAPH_WINDOW_HEIGHT = 250
GENERATE_GRAPH_WINDOW_WIDTH = 650

ADD_GRAPH_WINDOW_WIDTH = 550
ADD_GRAPH_WINDOW_HEIGHT = 250

ALGORITHMS_WINDOW_HEIGHT = 400
ALGORITHMS_WINDOW_WIDTH = 200

SAVE_GRAPH_WINDOW_HEIGHT = 100
SAVE_GRAPH_WINDOW_WIDTH = 275

LOAD_GRAPH_WINDOW_HEIGHT = 300
LOAD_GRAPH_WINDOW_WIDTH = 275

ALGORITHMS = 'Algorithms'
BFS = 'BFS'
DFS = 'DFS'
KRUSKAL_ALGORITHM = 'Kruskal Algorithm'
DIJKSTRA_ALGORITHM = 'Dijkstra Algorithm'
PRIM_ALGORITHM = 'Prim Algorithm'
ADD_GRAPH = 'Add Graph'
DIRECTED = 'Directed'
DIGRAPH = 'Digraph'
WEIGHTED = 'Weighted'
GENERATE_GRAPH = 'Generate Graph'

BUTTON_1 = "<Button-1>"

ADD_WEIGHT_WIDTH = 220
ADD_WEIGHT_HEIGHT = 80

COLOR_DELAY = 350
