from math import sqrt

# GRAPH
GRAPH_VIEW_WIDTH = 640
GRAPH_VIEW_HEIGHT = 600
RADIUS = 15
RADIUS_SQRT = sqrt(RADIUS)
VERTEX_FONT_SIZE = RADIUS
EDGE_WIDTH = 1.25
GRAPH_BG_COLOR = '#242424'
VERTEX_BG_COLOR = '#B4F8C8'
VERTEX_FG_COLOR = 'black'
EDGE_COLOR = '#D4F1F4'
APEX_DISTANCE = 55

WEIGHT_COLOR = '#B4F8C8'
WEIGHT_COLOR_CHANGE = 'cyan'

VERTEX_COLOR_CHANGE_BG = '#F8D210'
VERTEX_COLOR_CHANGE_FG = 'black'
EDGE_COLOR_CHANGE_BG = '#F8D210'

# BUTTON PANEL
BUTTONS_VIEW_WIDTH = 200
BUTTONS_VIEW_HEIGHT = 600
BUTTON_WIDTH = 30
BUTTON_HEIGHT = 5
BUTTONS_PANEL_BG_COLOR = '#164863'
BUTTONS_PANEL_SIZE_BG_COLOR = '#222831'
BUTTONS_PANEL_SIZE_FG_COLOR = '#EEEEEE'
BUTTON_BG_COLOR = '#222831'
BUTTON_FG_COLOR = '#EEEEEE'
FONT = "Oswald 13 bold"

# WINDOW
# WINDOW_HEIGHT = 600
# WINDOW_WIDTH = GRAPH_VIEW_WIDTH + BUTTONS_VIEW_WIDTH

WINDOW_HEIGHT = 450
WINDOW_WIDTH = 800

NEXT_TO_MAIN_WINDOW = WINDOW_WIDTH + 200
BELOW_MAIN_WINDOW = WINDOW_HEIGHT + 150

GENERATE_GRAPH_WINDOW_HEIGHT = 250
GENERATE_GRAPH_WINDOW_WIDTH = 650

ADD_GRAPH_WINDOW_WIDTH = 550
ADD_GRAPH_WINDOW_HEIGHT = 250

ALGORITHMS_WINDOW_HEIGHT = 400
ALGORITHMS_WINDOW_WIDTH = 200

ALGORITHMS = 'Algorithms'
BFS = 'BFS'
DFS = 'DFS'
KRUSKAL_ALGORITHM = 'Kruskal Algorithm'
ADD_GRAPH = 'Add Graph'
DIRECTED = 'Directed'
DIGRAPH = 'Digraph'
WEIGHTED = 'Weighted'
GENERATE_GRAPH = 'Generate Graph'
