GRAPH_VIEW_WIDTH = 640
GRAPH_VIEW_HEIGHT = 600

BUTTONS_VIEW_WIDTH = 200
BUTTONS_VIEW_HEIGHT = 600

WINDOW_HEIGHT = 600
WINDOW_WIDTH = GRAPH_VIEW_WIDTH + BUTTONS_VIEW_WIDTH

WINDOW_TITLE = "Graph Manager"
BUTTON_WIDTH = 30
BUTTON_HEIGHT = 5
BUTTON_BG = 'black'
BUTTON_FG = 'white'

RADIUS = 15
VERTEX_FONT_SIZE = RADIUS-2
EDGE_WIDTH = 1

GRAPH_BG_COLOR = 'black'
VERTEX_BG_COLOR = 'purple'
VERTEX_FG_COLOR = 'yellow'

BUTTONS_PANEL_BG_COLOR = 'purple'



