from math import sqrt

# GRAPH
GRAPH_VIEW_WIDTH = 640
GRAPH_VIEW_HEIGHT = 600
RADIUS = 15
RADIUS_SQRT = sqrt(RADIUS)
VERTEX_FONT_SIZE = RADIUS
EDGE_WIDTH = 1.25
GRAPH_BG_COLOR = '#242424'
VERTEX_BG_COLOR = '#00ADB5'
VERTEX_FG_COLOR = '#EEEEEE'
APEX_DISTANCE = 55

VERTEX_COLOR_CHANGE_BG = 'purple'
VERTEX_COLOR_CHANGE_FG = 'black'
EDGE_COLOR_CHANGE_BG = 'purple'

# BUTTON PANEL
BUTTONS_VIEW_WIDTH = 200
BUTTONS_VIEW_HEIGHT = 600
BUTTON_WIDTH = 30
BUTTON_HEIGHT = 5
BUTTONS_PANEL_BG_COLOR = '#164863'
BUTTONS_PANEL_SIZE_BG_COLOR = '#222831'
BUTTONS_PANEL_SIZE_FG_COLOR = '#EEEEEE'
BUTTON_BG_COLOR = '#222831'
BUTTON_FG_COLOR = '#EEEEEE'
FONT = "Oswald 13 bold"

# WINDOW
# WINDOW_HEIGHT = 600
# WINDOW_WIDTH = GRAPH_VIEW_WIDTH + BUTTONS_VIEW_WIDTH

WINDOW_HEIGHT = 580
WINDOW_WIDTH = 1100


ADD_GRAPH_WINDOW_HEIGHT = 320
ADD_GRAPH_WINDOW_WIDTH = 320
